"use client";
import Image from "next/image";
import { useState } from "react";
import { motion } from "framer-motion";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@radix-ui/react-tabs";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { Sample, Templates, Campaign, SendTest, SendReal } from "./ui/SelectTab";
import SelectTab from "./ui/SelectTab";
import Link from "next/link";

export default function UseComponent() {

    const [activeTab, setActiveTab] = useState("sample");

    return (
        <>
            <h2 className="text-2xl font-bold">How to Use</h2>
            <div className="md:ml-5 md:my-2 text-lg md:text-justify space-y-3">
                <p>
                    MuffinBite relies on a predefined directory structure to manage templates, data files, campaigns, and attachments.
                    The following section explains the purpose of each directory created during the initial setup.
                </p>
                <p>
                    MuffinBite generates 5 folders on the first run. (6th folder i.e. &quot;Logs&quot; is generated when we set debug to &quot;True&quot;)
                    <Image width={200} height={100} alt="" src="/demos/folder_structure.png" className="w-lg md:w-1/2 my-2 md:ml-5" />
                </p>
                <p>
                    The directories below are created automatically and are required for normal operation.
                </p>
                <ol className="m-2 md:ml-5 text-lg list-disc md:list-inside">
                    <li><strong>Attachments</strong>: Place all files you want to use as email attachments or embed inline in HTML templates in this folder.</li>
                    <li><strong>Campaigns</strong>: Stores all your campaigns. It is recommended <strong>not</strong> to make manual changes here.</li>
                    <li><strong>DataFiles</strong>: Store all your email records (CSV or Excel files) here for use in your outreach campaigns.</li>
                    <li><strong>EmailStatus</strong>: Contains the output files generated by MuffinBite, including records of successful and failed emails.</li>
                    <li><strong>Templates</strong>: Place all your HTML templates in this folder.</li>
                    <li><strong>Logs</strong>: Stores debug-level information in the <code>errors.log</code> file. This file is only created when debug mode is enabled.</li>
                </ol>
                <p>
                    The following steps demonstrate a complete workflow: preparing templates and data, creating a campaign,
                    and sending both test and real emails.
                </p>
                <Tabs className="hidden md:block mt-2" value={activeTab} onValueChange={setActiveTab}>
                    <div className="relative w-full">
                        <TabsList className="relative flex w-full bg-transparent rounded-full overflow-hidden">
                            {/* Animated slider */}
                            <motion.div
                                className="absolute top-[2px] left-[2px] h-[calc(100%-4px)] w-[calc(20%-4px)] bg-black/30 rounded-full"
                                animate={{
                                    x:
                                        activeTab === "sample" ? "0%" :
                                            activeTab === "templates" ? "100%" :
                                                activeTab === "campaign" ? "200%" :
                                                    activeTab === "test" ? "300%" :
                                                        "400%",
                                }}
                                transition={{ type: "spring", stiffness: 250, damping: 25 }}
                            />

                            <TabsTrigger
                                value="sample"
                                className="relative z-10 flex-1 text-center text-white py-2 font-medium cursor-pointer rounded-full data-[state=active]:bg-transparent"
                            >
                                Sample
                            </TabsTrigger>
                            <TabsTrigger
                                value="templates"
                                className="relative z-10 flex-1 text-center text-white py-2 font-medium cursor-pointer rounded-full data-[state=active]:bg-transparent"
                            >
                                1. Templates & Data
                            </TabsTrigger>
                            <TabsTrigger
                                value="campaign"
                                className="relative z-10 flex-1 text-center text-white py-2 font-medium cursor-pointer rounded-full data-[state=active]:bg-transparent"
                            >
                                2. Create Campaign
                            </TabsTrigger>
                            <TabsTrigger
                                value="test"
                                className="relative z-10 flex-1 text-center text-white py-2 font-medium cursor-pointer rounded-full data-[state=active]:bg-transparent"
                            >
                                3. Send Test
                            </TabsTrigger>
                            <TabsTrigger
                                value="real"
                                className="relative z-10 flex-1 text-center text-white py-2 font-medium cursor-pointer rounded-full data-[state=active]:bg-transparent"
                            >
                                4. Send Real
                            </TabsTrigger>
                        </TabsList>
                    </div>

                    <TabsContent className="mx-5 mt-4 overflow-y-auto element" value="sample">
                        <Sample />
                    </TabsContent>
                    <TabsContent className="mx-5 mt-4 overflow-y-auto element" value="templates">
                        <Templates />
                    </TabsContent>
                    <TabsContent className="mx-5 mt-4 overflow-y-auto element" value="campaign">
                        <Campaign />
                    </TabsContent>
                    <TabsContent className="mx-5 mt-4 overflow-y-auto element" value="test">
                        <SendTest />
                    </TabsContent>
                    <TabsContent className="mx-5 mt-4 overflow-y-auto element" value="real">
                        <SendReal />
                    </TabsContent>
                </Tabs>
                <div className="md:hidden   ">
                    <SelectTab />
                </div>
                <div className="mt-5 flex justify-between w-full">
                    <Link href="/docs/set_up"><span className="flex items-center justify-center gap-2"><ArrowLeft size={20} />Set Up</span> </Link>
                    <Link href="/docs/commands"><span className="flex items-center justify-center gap-2">Commands<ArrowRight size={20} /></span> </Link>
                </div>
            </div>
        </>
    )
}